version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ../Dockerfile
    container_name: colombo
    ports:
      - "8000:8000"
      - "4000:4000"
    env_file: .env
    volumes:
      - ../../:/code
    command: "npm run build && npm run start"
